sentry removal - WIP
ndlib/curate_nd pull request #1059
Opened 2023-08-10 15:46 UTC by EricDahl-NotreDame

This PR removes all references to Sentry from the project

2023-08-10 16:53 UTC, msuhovec commented on app/services/batch_ingestor.rb
This one I'd lime to keep- it is generated when (among other events) the night Thesis/Dissertation submissions fail, and if I see it, I'll requeue the submission.

2023-08-10 16:57 UTC, msuhovec requested changes
I asked to keep the Batch Ingest HTTP failure messgae- I am OK with deleting all of the others

2023-08-10 17:27 UTC, EricDahl-NotreDame commented on app/services/batch_ingestor.rb
No problem

2023-08-10 17:30 UTC, msuhovec approved these changes

2023-08-15 20:10 UTC, msuhovec approved these changes

2023-08-15 20:54 UTC, closed without merging